/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nhom1.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class BenhNhan extends javax.swing.JPanel {

    Connection conn;
    static int i = 0;
    String TCDate = "[0-3]\\d/[0-1]\\d/[1-2]{1}[0-9]{3}";

    public BenhNhan() {
        initComponents();
        checkNam.setSelected(true);
        create();
        lblSTT.setText(String.valueOf(100000 + ++i));
        Calendar cal = new GregorianCalendar();
        String a = "" + cal.get(Calendar.DAY_OF_MONTH) + "/" + (cal.get(Calendar.MONTH) + 1)
                + "/" + cal.get(Calendar.YEAR);
        txtNgayKham.setText(a);
    }

    public void create() {

        try {
            i = 0;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=BenhVien;"
                    + "username=sa;password=123");
            PreparedStatement ss = conn.prepareStatement("SELECT * FROM HoSoBenhNhan ");
            ResultSet as = ss.executeQuery();
            while (as.next()) {
                i++;
            }

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblSTT = new javax.swing.JLabel();
        checkNam = new javax.swing.JRadioButton();
        checkNu = new javax.swing.JRadioButton();
        warName = new javax.swing.JLabel();
        warTrieuChung = new javax.swing.JLabel();
        warRequest = new javax.swing.JLabel();
        warAddress = new javax.swing.JLabel();
        warDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayKham = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setPreferredSize(new java.awt.Dimension(1118, 805));

        txtName.setPreferredSize(new java.awt.Dimension(250, 26));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        txtSDT.setPreferredSize(new java.awt.Dimension(250, 26));

        txtAddress.setPreferredSize(new java.awt.Dimension(500, 26));
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });

        lblSTT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        checkNam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkNam.setText("Nam");
        checkNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNamActionPerformed(evt);
            }
        });

        checkNu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkNu.setText("Nữ");
        checkNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNuActionPerformed(evt);
            }
        });

        warName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warName.setForeground(new java.awt.Color(255, 51, 51));
        warName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        warName.setPreferredSize(new java.awt.Dimension(70, 20));

        warTrieuChung.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warTrieuChung.setForeground(new java.awt.Color(255, 51, 51));
        warTrieuChung.setPreferredSize(new java.awt.Dimension(70, 20));

        warRequest.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warRequest.setForeground(new java.awt.Color(255, 51, 51));
        warRequest.setPreferredSize(new java.awt.Dimension(70, 20));

        warAddress.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warAddress.setForeground(new java.awt.Color(255, 51, 51));
        warAddress.setPreferredSize(new java.awt.Dimension(70, 20));

        warDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warDate.setForeground(new java.awt.Color(255, 51, 51));
        warDate.setPreferredSize(new java.awt.Dimension(70, 20));
        warDate.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                warDateMouseWheelMoved(evt);
            }
        });

        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconAdd.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.setPreferredSize(new java.awt.Dimension(75, 29));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconCancel_1.png"))); // NOI18N
        jButton2.setText("Hủy");
        jButton2.setMaximumSize(new java.awt.Dimension(81, 33));
        jButton2.setMinimumSize(new java.awt.Dimension(81, 33));
        jButton2.setPreferredSize(new java.awt.Dimension(75, 33));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Họ tên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Ngày khám");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Số ĐT");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Địa chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("STT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Giới tính");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Ngày sinh");

        txtNgayKham.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(warTrieuChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(warName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSTT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(txtNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkNam)
                .addGap(12, 12, 12)
                .addComponent(checkNu))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(warDate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(warAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(880, 880, 880)
                .addComponent(warRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(warTrieuChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblSTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkNam)
                    .addComponent(checkNu))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(warDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(warRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNamActionPerformed
        if (checkNam.isSelected()) {
            checkNu.setSelected(false);
        } else {
            checkNu.setSelected(true);
        }
    }//GEN-LAST:event_checkNamActionPerformed

    private void checkNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNuActionPerformed
        if (checkNu.isSelected()) {
            checkNam.setSelected(false);
        } else {
            checkNam.setSelected(true);
        }
    }//GEN-LAST:event_checkNuActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if (txtName.getText().length() == 0) {
            warName.setText("Trống !");
        } else {
            warName.setText("");
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        if (txtAddress.getText().length() == 0) {
            warAddress.setText("Trống !");
        } else {
            warAddress.setText("");
        }
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost
        if (txtDate.getText().length() == 0) {
            warDate.setText("Trống !");
        } else {
            warDate.setText("");
        }
    }//GEN-LAST:event_txtDateFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtName.getText().length() == 0) {
            txtName.requestFocus();
        } else if (txtDate.getText().length() == 0) {
            txtDate.requestFocus();
        } else if (!txtDate.getText().matches(TCDate)) {
            txtDate.requestFocus();
        } else {
            try {
                PreparedStatement as = conn.prepareStatement("SELECT * FROM HoSoBenhNhan " + "where (Ten=?) and (NgaySinh=?)");
                as.setString(1, txtName.getText());
                as.setString(2, txtDate.getText());
                ResultSet ss = as.executeQuery();
                if (ss.next()) {
                    String a=ss.getString("TrangThai").trim();
                    PreparedStatement stmt = conn.prepareStatement(
                            "update HoSoBenhNhan "
                            + "set NgayKham= ?,"
                            + "TrangThai= ?,"
                            + "SDT= ?,"
                            + "DiaCHi=? "
                            + "where (Ten=?) and (NgaySinh=?)"
                    );
                    stmt.setString(1, txtNgayKham.getText());
                    stmt.setString(2, "chua kham");
                    stmt.setString(3, txtSDT.getText());
                    stmt.setString(4, txtAddress.getText());
                    stmt.setString(5, txtName.getText());
                    stmt.setString(6, txtDate.getText());
                    if (stmt.executeUpdate() > 0) {
                        if (a.equals("da kham")) JOptionPane.showMessageDialog(warName, "thêm thành công (tái khám)");
                        else if (a.equals("dang kham")) JOptionPane.showMessageDialog(warName, "thêm thành công (lấy kết quả)");
                        checkNam.setSelected(true);
                        checkNu.setSelected(false);
                        txtName.setText("");
                        txtDate.setText("");
                        txtSDT.setText("");
                        txtAddress.setText("");
                        lblSTT.setText(String.valueOf(100000 + i));
                    } else {
                        JOptionPane.showMessageDialog(warName, "thêm thất bại");
                    }
                } else {
                    PreparedStatement ps = conn.prepareStatement("INSERT INTO HoSoBenhNhan(MSBN, Ten, GioiTinh, NgaySinh, SDT, "
                            + "NgayKham,MSBS,KetQuaKhamBenh,SoLanKham, DiaCHi,TrangThai) "
                            + "VALUES(?,?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, lblSTT.getText());
                    ps.setString(2, txtName.getText());
                    if (checkNam.isSelected()) {
                        ps.setString(3, "Nam");
                    } else {
                        ps.setString(3, "Nu");
                    }
                    ps.setString(4, txtDate.getText());
                    ps.setString(5, txtSDT.getText());
                    ps.setString(6, txtNgayKham.getText());
                    ps.setString(7, "100000");
                    ps.setString(8, "");
                    ps.setInt(9, 0);
                    ps.setString(10, txtAddress.getText());
                    ps.setString(11, "chua kham");
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(warName, "thêm thành công");
                        checkNam.setSelected(true);
                        checkNu.setSelected(false);
                        txtName.setText("");
                        txtDate.setText("");
                        txtSDT.setText("");
                        txtAddress.setText("");
                        lblSTT.setText(String.valueOf(100000+ ++i));
                    } else {
                        JOptionPane.showMessageDialog(warName, "thêm thất bại");
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
                //}
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void warDateMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_warDateMouseWheelMoved

    }//GEN-LAST:event_warDateMouseWheelMoved

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        if (txtDate.isFocusable()) {
            warDate.setText("dd/mm/yyyy");
        } else {
            warDate.setText("");
        }
    }//GEN-LAST:event_txtDateFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        checkNam.setSelected(true);
        checkNu.setSelected(false);
        txtName.setText("");
        txtDate.setText("");
        txtSDT.setText("");
        txtAddress.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton checkNam;
    private javax.swing.JRadioButton checkNu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblSTT;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel txtNgayKham;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JLabel warAddress;
    private javax.swing.JLabel warDate;
    private javax.swing.JLabel warName;
    private javax.swing.JLabel warRequest;
    private javax.swing.JLabel warTrieuChung;
    // End of variables declaration//GEN-END:variables
}
