/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nhom1.view;

import Nhom1.controller.DAO;
import Nhom1.model.BacSi;
import Nhom1.model.DuocSi;
import Nhom1.model.TiepTan;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class DSTaiKhoan extends javax.swing.JPanel {

    int i = 1;
    ArrayList<BacSi> list1;
    ArrayList<DuocSi> list2;
    ArrayList<TiepTan> list3;
    DefaultTableModel model;

    public DSTaiKhoan() {
        initComponents();
        list1 = new DAO().getListBacSi();
        list2 = new DAO().getListDuocSi();
        list3 = new DAO().getListTiepTan();
        model = (DefaultTableModel) jTable1.getModel();
        showTable1();
        showTable2();
        showTable3();
    }

    public void showTable1() {
        for (BacSi s : list1) {
            if (s.getTrangThai().equals("1")) {
                model.addRow(new Object[]{
                    i++, s.getId(), s.getName(), "Bác sĩ", s.getEmail(), s.getSoDienThoai(), s.getUserName(), s.getMatKhau()
                });
            }
        }
    }

    public void showTable2() {
        for (DuocSi s : list2) {
            model.addRow(new Object[]{
                i++, s.getId(), s.getName(), "Dược sĩ", s.getEmail(), s.getSoDienThoai(), s.getUserName(), s.getMatKhau()
            });
        }
    }

    public void showTable3() {
        for (TiepTan s : list3) {
            model.addRow(new Object[]{
                i++, s.getId(), s.getName(), "Tiếp tân", s.getEmail(), s.getSoDienThoai(), s.getUserName(), s.getMatKhau()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setPreferredSize(new java.awt.Dimension(1118, 805));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Họ và tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 141, 0, 0);
        add(jLabel1, gridBagConstraints);

        jTextField1.setMinimumSize(new java.awt.Dimension(150, 26));
        jTextField1.setPreferredSize(new java.awt.Dimension(250, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 49, 0, 0);
        add(jTextField1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Chức vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 141, 0, 0);
        add(jLabel2, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bác sĩ", "Dược sĩ", "Tiếp tân" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 49, 0, 0);
        add(jComboBox1, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconFind.png"))); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 116, 12, 0);
        add(jButton1, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã số", "Họ và tên", "Chức vụ", "Email", "SĐT", "User", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 913;
        gridBagConstraints.ipady = 485;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 1);
        add(jPanel1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Trở về");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 26, 12, 0);
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int j = 1; j < i; j++) {
            model.removeRow(0);
        }
        i = 1;
        if (jTextField1.getText().equals("")) {
            if (jComboBox1.getSelectedItem().equals("Bác sĩ")) {
                for (BacSi s : list1) {
                    if (s.getTrangThai().equals("1")) {
                        model.addRow(new Object[]{
                            i++, s.getId(), s.getName(), "Bác sĩ", s.getEmail(), s.getSoDienThoai(), s.getUserName(), s.getMatKhau()
                        });
                    }
                }
            } else if (jComboBox1.getSelectedItem().equals("Dược sĩ")) {
                showTable2();
            } else {
                showTable3();
            }
        } else {
            if (jComboBox1.getSelectedItem().equals("Bác sĩ")) {
                for (BacSi s : list1) {
                    if ((s.getName().toLowerCase()).matches(".*"+jTextField1.getText().toLowerCase()+".*") && s.getTrangThai().equals("1")) {
                        model.addRow(new Object[]{
                            i++, s.getId(), s.getName(), "Bác sĩ", s.getEmail(), s.getSoDienThoai(), s.getUserName(), s.getMatKhau()
                        });
                    }
                }
            } else if (jComboBox1.getSelectedItem().equals("Dược sĩ")) {
                for (DuocSi s : list2) {
                    if ((s.getName().toLowerCase()).matches(".*"+jTextField1.getText().toLowerCase()+".*")) {
                        model.addRow(new Object[]{
                            i++, s.getId(), s.getName(), "Dược sĩ", s.getEmail(), s.getSoDienThoai(), s.getUserName(), s.getMatKhau()
                        });
                    }
                }
            } else {
                for (TiepTan s : list3) {
                    if ((s.getName().toLowerCase()).matches(".*"+jTextField1.getText().toLowerCase()+".*")) {
                        model.addRow(new Object[]{
                            i++, s.getId(), s.getName(), "Tiếp tân", s.getEmail(), s.getSoDienThoai(), s.getUserName(), s.getMatKhau()
                        });
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        i = 1;
        showTable1();
        showTable2();
        showTable3();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
