/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nhom1.view;

import Nhom1.model.DonThuoc;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioSystem;

/**
 *
 * @author Dell
 */
public class KhamBenh extends javax.swing.JPanel {

    DefaultTableModel model;
    int i = 1;
    private Connection conn;
    ArrayList<DonThuoc> list = new ArrayList<DonThuoc>();
    Login a = new Login();
    static String MSBN;

    public void playSound(String soundName) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();
        }
    }

    public KhamBenh() {
        initComponents();
        create();
        model = (DefaultTableModel) jTable1.getModel();
    }
    
    public void create() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=BenhVien;"
                    + "username=sa;password=123");

            PreparedStatement as = conn.prepareStatement("SELECT * FROM HoSoBenhNhan WHERE TrangThai=?");
            as.setString(1, "chua kham");
            ResultSet ss = as.executeQuery();
            lblName.setText(a.ten);
            if (ss.next()) {
                MSBN = ss.getString("MSBN").trim();
                txtNameBN.setText(ss.getString("Ten"));
                txtNgaySinh.setText(ss.getString("NgaySinh"));
                txtDiaChi.setText(ss.getString("DiaCHi"));
                jTextField1.setText(ss.getString("GioiTinh"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public int getSL() {
        int i = 0;
        try {
            PreparedStatement ps = conn.prepareStatement("select * from HoSoBenhNhan " + "where TrangThai=?");
            ps.setString(1, "chua kham");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                i++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChuanDoan = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNameBN = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        btnGoiBN = new javax.swing.JButton();
        btnBoQua = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTenThuoc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMinimumSize(new java.awt.Dimension(1118, 805));
        setPreferredSize(new java.awt.Dimension(1118, 805));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Họ tên BN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Giới tính");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Ngày sinh");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Địa chỉ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Kết quả");

        txtChuanDoan.setColumns(20);
        txtChuanDoan.setRows(5);
        txtChuanDoan.setPreferredSize(new java.awt.Dimension(150, 94));
        jScrollPane2.setViewportView(txtChuanDoan);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Kê đơn");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên thuốc", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        txtNameBN.setMinimumSize(new java.awt.Dimension(200, 26));
        txtNameBN.setPreferredSize(new java.awt.Dimension(200, 38));

        txtNgaySinh.setMinimumSize(new java.awt.Dimension(200, 26));
        txtNgaySinh.setPreferredSize(new java.awt.Dimension(200, 26));

        txtDiaChi.setMinimumSize(new java.awt.Dimension(200, 26));
        txtDiaChi.setPreferredSize(new java.awt.Dimension(200, 26));

        btnGoiBN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnGoiBN.setText("Khám xong");
        btnGoiBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiBNActionPerformed(evt);
            }
        });

        btnBoQua.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBoQua.setText("Bỏ qua");
        btnBoQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoQuaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Tên thuốc");

        txtTenThuoc.setPreferredSize(new java.awt.Dimension(150, 26));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Số lượng");

        txtSoluong.setPreferredSize(new java.awt.Dimension(150, 26));

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jTextField1.setPreferredSize(new java.awt.Dimension(6, 26));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Gọi BN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Bác sĩ:");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Khám chuyên khoa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnOK)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(221, 221, 221)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBoQua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoiBN)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBoQua)
                    .addComponent(jButton2)
                    .addComponent(btnGoiBN)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoiBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoiBNActionPerformed
        try {
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM HoSoBenhNhan WHERE MSBN=?");
            ps.setString(1, MSBN);
            ResultSet rs = ps.executeQuery();
            rs.next();
            PreparedStatement xs = conn.prepareStatement("DELETE FROM DonThuoc where MSBN=? ");
            xs.setString(1, MSBN);
            xs.executeUpdate();
            PreparedStatement stmt = conn.prepareStatement(
                    "update HoSoBenhNhan "
                    + "set KetQuaKhamBenh= ?,"
                    + "SoLanKham= ?,"
                    + "TrangThai=?,"
                    + "MSBS=? "
                    + "where MSBN=?"
            );
            stmt.setString(1, rs.getString("KetQuaKhamBenh").trim() + "Lần" + (rs.getInt("SoLanKham") + 1) + ": " + txtChuanDoan.getText() + ". ");
            stmt.setInt(2, rs.getInt("SoLanKham") + 1);
            stmt.setString(3, "da kham");
            stmt.setString(4,a.ms);
            stmt.setString(5, MSBN);
            stmt.executeUpdate();

            for (DonThuoc s : list) {

                PreparedStatement ms = conn.prepareStatement("INSERT INTO DonThuoc(MSBN,MSThuoc,SoLuongThuocDung)" + "VALUES(?,?,?)");
                ms.setString(1, MSBN);
                ms.setString(2, s.getMSThuoc());
                ms.setInt(3, s.getSoLuong());
                ms.executeUpdate();

            }
            PreparedStatement as = conn.prepareStatement("SELECT * FROM HoSoBenhNhan WHERE TrangThai=?");
            as.setString(1, "chua kham");

            ResultSet ss = as.executeQuery();

            if (ss.next()) {

                MSBN = ss.getString("MSBN").trim();
                txtNameBN.setText(ss.getString("Ten"));
                txtNgaySinh.setText(ss.getString("NgaySinh"));
                txtDiaChi.setText(ss.getString("DiaCHi"));
                jTextField1.setText(ss.getString("GioiTinh"));
            } else {

                txtNameBN.setText("");
                txtNgaySinh.setText("");
                txtDiaChi.setText("");
                jTextField1.setText("");
            }
            int m = model.getRowCount();
            for (int j = 1; j <= m; j++) {
                model.removeRow(0);
            }
            txtChuanDoan.setText("");
            Login x = new Login();
            list.clear();
            x.frame.set();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGoiBNActionPerformed

    private void btnBoQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoQuaActionPerformed
        try {
            PreparedStatement stmt = conn.prepareStatement(
                    "update HoSoBenhNhan "
                    + "set TrangThai= ? "
                    + "where MSBN=?"
            );
            stmt.setString(1, "da kham");
            stmt.setString(2, MSBN);
            stmt.executeUpdate();
            PreparedStatement as = conn.prepareStatement("SELECT * FROM HoSoBenhNhan WHERE TrangThai=?");
            as.setString(1, "chua kham");
            ResultSet ss = as.executeQuery();
            if (ss.next()) {

                MSBN = ss.getString("MSBN").trim();
                txtNameBN.setText(ss.getString("Ten"));
                txtNgaySinh.setText(ss.getString("NgaySinh"));
                txtDiaChi.setText(ss.getString("DiaCHi"));
                jTextField1.setText(ss.getString("GioiTinh"));
            } else {
                txtNameBN.setText("");
                txtNgaySinh.setText("");
                txtDiaChi.setText("");
                jTextField1.setText("");

            }
            int m = model.getRowCount();
            for (int j = 1; j <= m; j++) {
                model.removeRow(0);
            }
            txtChuanDoan.setText("");
            txtTenThuoc.setText("");
            txtSoluong.setText("");
            Login x = new Login();
            list.clear();
            x.frame.set();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBoQuaActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if(txtTenThuoc.getText().length()==0){
            txtTenThuoc.requestFocus();
        }
        else if(txtSoluong.getText().length()==0){
            txtSoluong.requestFocus();
        }
        else{
            try {
            PreparedStatement stmt = conn.prepareStatement("SELECT * FROM DanhSachThuoc WHERE TenThuoc=?");
            stmt.setString(1, txtTenThuoc.getText());
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                    try {
                    int a = Integer.parseInt(txtSoluong.getText());
                    DonThuoc x = new DonThuoc();
                    x.setMSBN(MSBN);
                    x.setMSThuoc(rs.getString("MSThuoc"));
                    x.setSoLuong(a);
                    list.add(x);
                    model.addRow(new Object[]{
                        jTable1.getRowCount() + 1, txtTenThuoc.getText(), a
                    });
                    txtTenThuoc.setText("");
                    txtSoluong.setText("");   
                } catch (Exception e) {
                    txtSoluong.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(btnOK, "Không tồn tại thuốc");
            }
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        list.clear();
        int m = model.getRowCount();
        for (int j = 1; j <= m; j++) {
            model.removeRow(0);
        }
        txtTenThuoc.setText("");
        txtSoluong.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        playSound("a.wav");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            PreparedStatement stmt = conn.prepareStatement(
                    "update HoSoBenhNhan "
                    + "set TrangThai= ? "
                    + "where MSBN=?"
            );
            stmt.setString(1, "dang kham");
            stmt.setString(2, MSBN);
            stmt.executeUpdate();
            PreparedStatement as = conn.prepareStatement("SELECT * FROM HoSoBenhNhan WHERE TrangThai=?");
            as.setString(1, "chua kham");
            ResultSet ss = as.executeQuery();
            if (ss.next()) {

                MSBN = ss.getString("MSBN").trim();
                txtNameBN.setText(ss.getString("Ten"));
                txtNgaySinh.setText(ss.getString("NgaySinh"));
                txtDiaChi.setText(ss.getString("DiaCHi"));
                jTextField1.setText(ss.getString("GioiTinh"));
                //lblName.setText(a.ten);
            } else {
                txtNameBN.setText("");
                txtNgaySinh.setText("");
                txtDiaChi.setText("");
                jTextField1.setText("");

            }
            int m = model.getRowCount();
            for (int j = 1; j <= m; j++) {
                model.removeRow(0);
            }
            txtChuanDoan.setText("");
            txtTenThuoc.setText("");
            txtSoluong.setText("");
            Login x = new Login();
            list.clear();
            x.frame.set();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoQua;
    private javax.swing.JButton btnGoiBN;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextArea txtChuanDoan;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtNameBN;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenThuoc;
    // End of variables declaration//GEN-END:variables
}
