/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nhom1.view;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import static java.sql.DriverManager.getConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {

    static String taikhoan, loaitk, pass, ten,ms;
    JPanel childPanel;
    static MainForm frame;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void AddPanel(JPanel panel) {
        childPanel = panel;
        jPanel2.removeAll();
        jPanel2.add(childPanel);
        jPanel2.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        btnLog = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        warUser = new javax.swing.JLabel();
        warPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnLog.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconLog.png"))); // NOI18N
        btnLog.setText("Đăng nhập");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 43, 155, 0);
        jPanel2.add(btnLog, gridBagConstraints);

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUser.setText("Tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 187, 0, 0);
        jPanel2.add(lblUser, gridBagConstraints);

        lblPass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPass.setText("Mật khẩu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 187, 0, 0);
        jPanel2.add(lblPass, gridBagConstraints);

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconCancel_1.png"))); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 18, 155, 0);
        jPanel2.add(btnCancel, gridBagConstraints);

        txtUser.setPreferredSize(new java.awt.Dimension(46, 26));
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 195;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 40, 0, 0);
        jPanel2.add(txtUser, gridBagConstraints);

        warUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warUser.setForeground(new java.awt.Color(255, 0, 102));
        warUser.setPreferredSize(new java.awt.Dimension(80, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 40, 0, 148);
        jPanel2.add(warUser, gridBagConstraints);

        warPass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warPass.setForeground(new java.awt.Color(255, 0, 102));
        warPass.setPreferredSize(new java.awt.Dimension(80, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 40, 0, 148);
        jPanel2.add(warPass, gridBagConstraints);

        txtPass.setPreferredSize(new java.awt.Dimension(46, 26));
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 195;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 40, 0, 0);
        jPanel2.add(txtPass, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jPanel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Đăng nhập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(162, 72, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(1201, 100));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel4.setText("Bệnh viện đa khoa Bạch Mai");
        jLabel4.setMaximumSize(new java.awt.Dimension(350, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(350, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(350, 25));
        jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txtUser.setText("");
        txtPass.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        if (txtUser.getText().length() == 0) {
            txtUser.requestFocus();
        } else if (txtPass.getText().length() == 0) {
            txtPass.requestFocus();
        } else if (txtUser.getText().equals("admin") && txtPass.getText().equals("123456")) {
            frame = new MainForm(4);
            setVisible(false);
            frame.setVisible(true);
        } else {
            try {
                Connection conn = getConnection("jdbc:sqlserver://localhost:1433;databasename=BenhVien;"
                        + "username=sa;password=123");
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(
                        "select * from dbo.TaiKhoanDangNhap "
                        + "where (User_Name='" + txtUser.getText() + "' )and (Pass_Word= '" + txtPass.getText() + "') "
                );
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(rootPane, "tài khoản hoặc mật khẩu không đúng");
                } else {
                    if (rs.getString("TrangThai").trim().equals("1")) {
                        this.taikhoan = txtUser.getText();
                        this.loaitk = rs.getString("LoaiTK").trim();
                        this.pass = rs.getString("Pass_Word").trim();

                        if (loaitk.equals("bac si")) {
                            frame = new MainForm(1);
                            setVisible(false);
                            frame.setVisible(true);
                            PreparedStatement ss = conn.prepareStatement("SELECT * FROM DanhSachBacSi where Username=? ");
                            ss.setString(1, taikhoan);
                            ResultSet as = ss.executeQuery();
                            as.next();
                            ten = as.getString("Ten").trim();
                            ms=as.getString("MSBS").trim();
                        } else if (loaitk.equals("ban thuoc")) {
                            frame = new MainForm(2);
                            setVisible(false);
                            frame.setVisible(true);
                            PreparedStatement ss = conn.prepareStatement("SELECT * FROM DanhSachnguoiBanThuoc where UserName=? ");
                            ss.setString(1, taikhoan);
                            ResultSet as = ss.executeQuery();
                            as.next();
                            ten = as.getString("Ten").trim();
                        } else if (loaitk.equals("phat so")) {
                            frame = new MainForm(3);
                            setVisible(false);
                            frame.setVisible(true);
                            PreparedStatement ss = conn.prepareStatement("SELECT * FROM DanhSachNguoiPhatSo where UserName=? ");
                            ss.setString(1, taikhoan);
                            ResultSet as = ss.executeQuery();
                            as.next();
                            ten = as.getString("Ten").trim();
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "tài khoản hoặc mật khẩu không đúng");
                    }
                }
                conn.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed

    }//GEN-LAST:event_txtPassActionPerformed

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        if (txtUser.getText().equals("")) {
            warUser.setText("Trống !");
        } else {
            warUser.setText("");
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        if (txtPass.getText().equals("")) {
            warPass.setText("Trống !");
        } else {
            warPass.setText("");
        }
    }//GEN-LAST:event_txtPassFocusLost

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPass.requestFocus();
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLog.doClick();
        }
    }//GEN-LAST:event_txtPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLog;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel warPass;
    private javax.swing.JLabel warUser;
    // End of variables declaration//GEN-END:variables
}
