/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nhom1.view;

import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Dell
 */
public class MainForm extends javax.swing.JFrame {

    Calendar cal;

    public MainForm() {
        cal = new GregorianCalendar();
        initComponents();
        setLocationRelativeTo(null);
        lblTime.setText("Hà Nội, " + "ngày " + cal.get(Calendar.DAY_OF_MONTH)
                + " tháng " + (cal.get(Calendar.MONTH) + 1) + " năm " + cal.get(Calendar.YEAR));
    }

    public MainForm(int i) {
        cal = new GregorianCalendar();
        initComponents();
        setLocationRelativeTo(null);
        lblTime.setText("Hà Nội, " + "ngày " + cal.get(Calendar.DAY_OF_MONTH)
                + " tháng " + (cal.get(Calendar.MONTH) + 1) + " năm " + cal.get(Calendar.YEAR));
        if (i == 1) {
            BacSi();
        }
        if (i == 2) {
            DuocSi();
        }
        if (i == 3) {
            TiepTan();
        }
        if (i == 4) {
            Admin();
        }
    }

    public void BacSi() {
        mnDonTiep.hide();
        mnNhaThuoc.hide();
        jMenu1.hide();
    }

    public void DuocSi() {
        mnDonTiep.hide();
        mnKhamBenh.hide();
        jMenu2.hide();
        jMenu1.hide();
    }

    public void TiepTan() {
        mnKhamBenh.hide();
        mnNhaThuoc.hide();
        jMenu1.hide();
        jMenu2.hide();
        mnThuNgan.hide();
    }

    public void Admin() {
        mnDonTiep.hide();
        mnNhaThuoc.hide();
        jMenu2.hide();
        mnNguoiDung.hide();
        mnKhamBenh.hide();
    }

    public void set() {
        KhamBenh a = new KhamBenh();
        lblSoLuong.setText("Số lượng bệnh nhân đang chờ : " + a.getSL());
    }

    public void AddPanel(JPanel panel) {
        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.validate();
        mainPanel.setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        mn = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnTrangChu = new javax.swing.JMenu();
        mnDonTiep = new javax.swing.JMenu();
        mnThemBN = new javax.swing.JMenuItem();
        mnThuNgan = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnKhamBenh = new javax.swing.JMenu();
        mnNhaThuoc = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnNguoiDung = new javax.swing.JMenu();
        mnTTCaNhan = new javax.swing.JMenuItem();
        mnTTTaiKhoan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mnXoaUser = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnDSTK = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setPreferredSize(new java.awt.Dimension(1200, 1000));

        mainPanel.setBackground(new java.awt.Color(255, 204, 204));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainPanel.setPreferredSize(new java.awt.Dimension(660, 371));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/benhvien.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 250, 0, 0);
        mainPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("BỆNH VIỆN ĐA KHOA BẠCH MAI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(50, 20, 0, 0);
        mainPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Hotline: 01639629043");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(110, 200, 359, 0);
        mainPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Email : bvbachmai@gmail.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(110, 320, 359, 220);
        mainPanel.add(jLabel4, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 40));

        lblTime.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblTime.setPreferredSize(new java.awt.Dimension(52, 20));

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblSoLuong.setPreferredSize(new java.awt.Dimension(150, 26));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 494, Short.MAX_VALUE)
                                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        mnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/home.png"))); // NOI18N
        mnTrangChu.setText("Trang chủ");
        mnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnTrangChuMouseClicked(evt);
            }
        });
        mnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTrangChuActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnTrangChu);

        mn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconLogoutt.png"))); // NOI18N
        mn.setText("Đăng xuất");
        mn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMouseClicked(evt);
            }
        });
//        mn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                mnActionPerformed(evt);
//            }
//        });

        mnDonTiep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconLeTan.png"))); // NOI18N
        mnDonTiep.setText("Đón tiếp");

        mnThemBN.setText("Thêm bệnh nhân");
        mnThemBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThemBNActionPerformed(evt);
            }
        });
        mnDonTiep.add(mnThemBN);

        mnThuNgan.setText("Thu ngân");
        mnThuNgan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThuNganActionPerformed(evt);
            }
        });
        mnDonTiep.add(mnThuNgan);

        jMenuItem5.setText("DS BN chờ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnDonTiep.add(jMenuItem5);

        jMenuBar1.add(mnDonTiep);

        mnKhamBenh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconBanThuoc.png"))); // NOI18N
        mnKhamBenh.setText("Khám bệnh");
        mnKhamBenh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnKhamBenhMousePressed(evt);
            }
        });
        mnKhamBenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKhamBenhActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnKhamBenh);

        mnNhaThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconKhamBenh.png"))); // NOI18N
        mnNhaThuoc.setText("Nhà thuốc");

        jMenuItem1.setText("Bán thuốc");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnNhaThuoc.add(jMenuItem1);

        jMenuItem4.setText("Nhập thuốc");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnNhaThuoc.add(jMenuItem4);

        jMenuBar1.add(mnNhaThuoc);

        mnNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconUser.png"))); // NOI18N
        mnNguoiDung.setText("Người dùng");

        mnTTCaNhan.setText("TT cá nhân");
        mnTTCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTTCaNhanActionPerformed(evt);
            }
        });
        mnNguoiDung.add(mnTTCaNhan);

        mnTTTaiKhoan.setText("TT tài khoản");
        mnTTTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTTTaiKhoanActionPerformed(evt);
            }
        });
        mnNguoiDung.add(mnTTTaiKhoan);

        jMenuBar1.add(mnNguoiDung);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/view/iconDoc.png"))); // NOI18N
        jMenu2.setText("Hồ sơ BN");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nhom1/iconSystem.png"))); // NOI18N
        jMenu1.setText("Hệ thống");

        mnXoaUser.setText("Thêm tài khoản");
        mnXoaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXoaUserActionPerformed(evt);
            }
        });
        jMenu1.add(mnXoaUser);

        jMenuItem3.setText("Xóa tài khoản");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        mnDSTK.setText("DS Tài khoản");
        mnDSTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDSTKActionPerformed(evt);
            }
        });
        jMenu1.add(mnDSTK);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        jMenuBar1.add(mn);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTrangChuActionPerformed
        AddPanel(new Home());
        lblSoLuong.setText("");
    }//GEN-LAST:event_mnTrangChuActionPerformed

    private void mnThemBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThemBNActionPerformed
        AddPanel(new BenhNhan());
        lblSoLuong.setText("");
    }//GEN-LAST:event_mnThemBNActionPerformed

    private void mnTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTrangChuMouseClicked
        AddPanel(new Home());
        lblSoLuong.setText("");
    }//GEN-LAST:event_mnTrangChuMouseClicked

    private void mnMouseClicked(java.awt.event.MouseEvent evt) {
        JFrame jfr = new Login();
        jfr.setVisible(true);
        setVisible(false);
    }

    private void mnTTCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTTCaNhanActionPerformed
        AddPanel(new TTCaNhan());
        lblSoLuong.setText("");
    }//GEN-LAST:event_mnTTCaNhanActionPerformed

    private void mnTTTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTTTaiKhoanActionPerformed
        AddPanel(new TTTaiKhoan());
        lblSoLuong.setText("");
    }//GEN-LAST:event_mnTTTaiKhoanActionPerformed

    private void mnXoaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXoaUserActionPerformed
        AddPanel(new ThemTK());
        lblSoLuong.setText("");
    }//GEN-LAST:event_mnXoaUserActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AddPanel(new XoaTK());
        lblSoLuong.setText("");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnDSTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDSTKActionPerformed
        AddPanel(new DSTaiKhoan());
        lblSoLuong.setText("");
    }//GEN-LAST:event_mnDSTKActionPerformed

    private void mnKhamBenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKhamBenhActionPerformed
        //lblSoLuong.setText("So luong benh nhan cho :"+ new DSBNCho().getSoLuongBN());
    }//GEN-LAST:event_mnKhamBenhActionPerformed

    private void mnKhamBenhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnKhamBenhMousePressed
        KhamBenh a = new KhamBenh();
        AddPanel(a);
        lblSoLuong.setText("Số lượng bệnh nhân đang chờ : " + a.getSL());
    }//GEN-LAST:event_mnKhamBenhMousePressed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AddPanel(new DSBNCho());
        lblSoLuong.setText("");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnThuNganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThuNganActionPerformed
        AddPanel(new ThuNgan());
        lblSoLuong.setText("");
    }//GEN-LAST:event_mnThuNganActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AddPanel(new BanThuoc());
        lblSoLuong.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        lblSoLuong.setText("");
        AddPanel(new NhapThuoc());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        AddPanel(new HoSoBNn());
    }//GEN-LAST:event_jMenu2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem mnDSTK;
    private javax.swing.JMenu mnDonTiep;
    private javax.swing.JMenu mnKhamBenh;
    private javax.swing.JMenu mnNguoiDung;
    private javax.swing.JMenu mnNhaThuoc;
    private javax.swing.JMenuItem mnTTCaNhan;
    private javax.swing.JMenuItem mnTTTaiKhoan;
    private javax.swing.JMenuItem mnThemBN;
    private javax.swing.JMenuItem mnThuNgan;
    private javax.swing.JMenu mnTrangChu;
    private javax.swing.JMenu mn;
    private javax.swing.JMenuItem mnXoaUser;
    // End of variables declaration//GEN-END:variables
}
