/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nhom1.view;

import Nhom1.controller.DAO;
import Nhom1.model.BacSi;
import Nhom1.model.DuocSi;
import Nhom1.model.TiepTan;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ThemTK extends javax.swing.JPanel {

    private Connection conn;
    String TCEmail = "\\w{1,}_{0,1}\\w{0,}@\\w{1,}.{0,1}\\w{0,}.{0,1}\\w{0,}.{0,1}\\w{0,}.{0,1}\\w{0,}";
    String TCSDT = "0\\d{9,10}";
    String TCID[] = {"\\d{9}", "\\d{12}"};
    String TCPass = "\\w{6,}";
    String TCDate = "[0-3]\\d/[0-1]\\d/[1-2]\\d{3}";
    ArrayList<BacSi> list;
    ArrayList<DuocSi> list1;
    ArrayList<TiepTan> list2;
    DefaultTableModel model;

    public ThemTK() {
        initComponents();
        checkNam.setSelected(true);
        checkNam.setSelected(true);
        list = new DAO().getListBacSi();
        list1 = new DAO().getListDuocSi();
        list2 = new DAO().getListTiepTan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtJob = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        checkNam = new javax.swing.JRadioButton();
        checkNu = new javax.swing.JRadioButton();
        txtSDT = new javax.swing.JTextField();
        warName = new javax.swing.JLabel();
        warSDT = new javax.swing.JLabel();
        warID = new javax.swing.JLabel();
        warEmail = new javax.swing.JLabel();
        warDiaChi = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        warDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JPasswordField();
        txtConfirmPass = new javax.swing.JPasswordField();
        warUser = new javax.swing.JLabel();
        warNewPass = new javax.swing.JLabel();
        warConfirmPass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1118, 805));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setPreferredSize(new java.awt.Dimension(843, 370));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Họ và tên");
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Chức vụ");
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Số CMND");
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Giới tính");
        jLabel14.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Số ĐT");
        jLabel15.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Email");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Địa chỉ");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Ngày sinh");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 20));

        txtName.setPreferredSize(new java.awt.Dimension(250, 26));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        txtJob.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bác sĩ", "Dược sĩ", "Tiếp tân" }));

        txtID.setPreferredSize(new java.awt.Dimension(250, 26));
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });

        txtEmail.setPreferredSize(new java.awt.Dimension(250, 26));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        txtAddress.setPreferredSize(new java.awt.Dimension(250, 26));
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });

        checkNam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkNam.setText("Nam");
        checkNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNamActionPerformed(evt);
            }
        });

        checkNu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkNu.setText("Nữ");
        checkNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNuActionPerformed(evt);
            }
        });

        txtSDT.setPreferredSize(new java.awt.Dimension(250, 26));
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });

        warName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warName.setForeground(new java.awt.Color(255, 51, 51));
        warName.setPreferredSize(new java.awt.Dimension(150, 26));

        warSDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warSDT.setForeground(new java.awt.Color(255, 51, 51));
        warSDT.setPreferredSize(new java.awt.Dimension(150, 26));

        warID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warID.setForeground(new java.awt.Color(255, 51, 51));
        warID.setPreferredSize(new java.awt.Dimension(150, 26));

        warEmail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warEmail.setForeground(new java.awt.Color(255, 51, 51));
        warEmail.setPreferredSize(new java.awt.Dimension(150, 26));

        warDiaChi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warDiaChi.setForeground(new java.awt.Color(255, 51, 51));
        warDiaChi.setPreferredSize(new java.awt.Dimension(150, 26));

        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });

        warDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warDate.setForeground(new java.awt.Color(255, 51, 51));
        warDate.setPreferredSize(new java.awt.Dimension(150, 26));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(warName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(checkNam)
                        .addGap(1, 1, 1)
                        .addComponent(checkNu))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(warSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(warDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(warID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(warEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(warDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkNam)
                    .addComponent(checkNu))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Tài khoản");

        txtUser.setPreferredSize(new java.awt.Dimension(250, 26));
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Mật khẩu");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Xác nhận MK");

        txtNewPass.setPreferredSize(new java.awt.Dimension(250, 26));
        txtNewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPassFocusLost(evt);
            }
        });

        txtConfirmPass.setPreferredSize(new java.awt.Dimension(250, 26));
        txtConfirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPassFocusLost(evt);
            }
        });
        txtConfirmPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmPassKeyPressed(evt);
            }
        });

        warUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warUser.setForeground(new java.awt.Color(255, 51, 51));
        warUser.setPreferredSize(new java.awt.Dimension(150, 20));

        warNewPass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warNewPass.setForeground(new java.awt.Color(255, 51, 51));
        warNewPass.setPreferredSize(new java.awt.Dimension(150, 20));

        warConfirmPass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        warConfirmPass.setForeground(new java.awt.Color(255, 51, 51));
        warConfirmPass.setPreferredSize(new java.awt.Dimension(150, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Hủy");
        jButton2.setPreferredSize(new java.awt.Dimension(73, 29));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(64, 64, 64))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(41, 41, 41)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(warUser, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(warNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(168, 168, 168))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(warUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(warNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(warConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained

    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        if (txtUser.getText().length() == 0) {
            warUser.setText("Trống !");

        } else {
            warUser.setText("");
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

    }//GEN-LAST:event_txtUserActionPerformed

    private void txtNewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPassFocusGained
        if (txtNewPass.isFocusable()) {
            warNewPass.setText("Ít nhất 6 kí tự");
        } else {
            warNewPass.setText("");
        }
    }//GEN-LAST:event_txtNewPassFocusGained

    private void txtNewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPassFocusLost
        if (txtNewPass.getText().length() == 0) {
            warNewPass.setText("Trống !");
        } else {
            warNewPass.setText("");
        }
    }//GEN-LAST:event_txtNewPassFocusLost

    private void txtConfirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPassFocusLost
        if (txtConfirmPass.getText().length() == 0) {
            warConfirmPass.setText("Trống !");
        } else {
            warConfirmPass.setText("");
        }
    }//GEN-LAST:event_txtConfirmPassFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.isFocusable()) {
            warEmail.setText("abc@xyz");
        } else {
            warEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if (txtName.getText().length() == 0) {
            warName.setText("Trống !");
        } else {
            warName.setText("");
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        if (txtSDT.getText().length() == 0) {
            warSDT.setText("Trống !");
        } else {
            warSDT.setText("");
        }
    }//GEN-LAST:event_txtSDTFocusLost

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost
        if (txtDate.getText().length() == 0) {
            warDate.setText("Trống !");
        } else {
            warDate.setText("");
        }
    }//GEN-LAST:event_txtDateFocusLost

    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
        if (txtID.getText().length() == 0) {
            warID.setText("Trống !");
        } else {
            warID.setText("");
        }
    }//GEN-LAST:event_txtIDFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().length() == 0) {
            warEmail.setText("Trống !");
        } else {
            warEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        if (txtAddress.getText().length() == 0) {
            warDiaChi.setText("Trống !");
        } else {
            warDiaChi.setText("");
        }
    }//GEN-LAST:event_txtAddressFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtName.getText().length() == 0) {
            warName.setText("Trống !");
            txtName.requestFocus();
        } else if (txtAddress.getText().length() == 0) {
            warDiaChi.setText("Trống !");
            txtAddress.requestFocus();
        } else if (txtConfirmPass.getText().length() == 0) {
            warConfirmPass.setText("Trống !");
            txtConfirmPass.requestFocus();
        } else if (txtDate.getText().length() == 0) {
            warDate.setText("Trống !");
            txtDate.requestFocus();
        } else if (txtEmail.getText().length() == 0) {
            warEmail.setText("Trống !");
            txtEmail.requestFocus();
        } else if (txtID.getText().length() == 0) {
            warID.setText("Trống !");
            txtID.requestFocus();
        } else if (txtNewPass.getText().length() == 0) {
            warNewPass.setText("Trống !");
            txtNewPass.requestFocus();
        } else if (txtSDT.getText().length() == 0) {
            warSDT.setText("Trống !");
            txtSDT.requestFocus();
        } else if (txtUser.getText().length() == 0) {
            warUser.setText("Trống !");
            txtUser.requestFocus();
        } else if (!txtNewPass.getText().equals(txtConfirmPass.getText())) {
            warConfirmPass.setText("Mật khẩu không trùng khớp");
            txtConfirmPass.requestFocus();
        } else if (!txtNewPass.getText().matches(TCPass)) {
            warNewPass.setText("Thông tin không chính xác! ");
            txtNewPass.requestFocus();
        } else if (!txtSDT.getText().matches(TCSDT)) {
            warSDT.setText("Thông tin không chính xác! ");
            txtSDT.requestFocus();
        } else if (!txtEmail.getText().matches(TCEmail)) {
            warEmail.setText("Thông tin không chính xác! ");
            txtEmail.requestFocus();
        } else if (!txtID.getText().matches(TCID[0]) && !txtID.getText().matches(TCID[1])) {
            warID.setText("Thông tin không chính xác! ");
            txtID.requestFocus();
        } else if (!txtDate.getText().matches(TCDate)) {
            warDate.setText("Thông tin không chính xác! ");
            txtDate.requestFocus();
        } else {
            warConfirmPass.setText("");
            if (txtJob.getSelectedItem().equals("Bác sĩ")) {
                BacSi s = new BacSi();

                try {
                    try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ThemTK.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=BenhVien;"
                            + "username=sa;password=123");
                    Statement ps = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                            ResultSet.CONCUR_READ_ONLY);
                    ResultSet rs = ps.executeQuery("select * from DanhSachBacSi");
                    if (!rs.next()) {
                        s.setMSBS("100000");
                    } else {
                        rs.last();
                        String a = rs.getString("MSBS").trim();
                        //a = a.substring(2);
                        a = "" + (Integer.parseInt(a) + 1);
                        s.setMSBS(a);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ThemTK.class.getName()).log(Level.SEVERE, null, ex);
                }

                s.setName(txtName.getText());

                if (checkNam.isSelected()) {
                    s.setGioiTinh("Nam");
                } else if (checkNu.isSelected()) {
                    s.setGioiTinh("Nữ");
                }
                s.setNgaySinh(txtDate.getText());
                s.setSoDienThoai(txtSDT.getText());
                s.setDiaChi(txtAddress.getText());
                s.setMatKhau(txtNewPass.getText());
                s.setUserName(txtUser.getText());
                s.setEmail(txtEmail.getText());
                s.setCMND(txtID.getText());
                if (new DAO().addTKDoctor(s) && (new DAO()).addDoctor(s)) {
                    JOptionPane.showMessageDialog(txtDate, "thêm thành công");
                    list.add(s);
                } else {
                    JOptionPane.showMessageDialog(txtDate, "tài khoản đã tồn tại");
                }
            }
            if (txtJob.getSelectedItem().equals("Dược sĩ")) {
                DuocSi s = new DuocSi();
                try {
                    try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ThemTK.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=BenhVien;"
                            + "username=sa;password=123");
                    Statement ps = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                            ResultSet.CONCUR_READ_ONLY);
                    ResultSet rs = ps.executeQuery("select * from DanhSachNguoibanThuoc");
                    if (!rs.next()) {
                        s.setMSNV("200000");
                    } else {
                        rs.last();
                        String a = rs.getString("MSNV").trim();
                        //a = a.substring(2);
                        a = "" + (Integer.parseInt(a) + 1);
                        s.setMSNV(a);
                    }

                    s.setName(txtName.getText());
                    if (checkNam.isSelected()) {
                        s.setGioiTinh("Nam");
                    } else if (checkNu.isSelected()) {
                        s.setGioiTinh("Nữ");
                    }
                    s.setNgaySinh(txtDate.getText());
                    s.setSoDienThoai(txtSDT.getText());
                    s.setDiaChi(txtAddress.getText());
                    s.setMatKhau(txtNewPass.getText());
                    s.setUserName(txtUser.getText());
                    s.setEmail(txtEmail.getText());
                    s.setCMND(txtID.getText());
                    if (new DAO().addTKDuocSi(s) && (new DAO()).addDuocSi(s)) {
                        JOptionPane.showMessageDialog(txtDate, "thêm thành công");
                        list1.add(s);
                    } else {
                        JOptionPane.showMessageDialog(txtDate, "tài khoản đã tồn tại");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ThemTK.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (txtJob.getSelectedItem().equals("Tiếp tân")) {
                TiepTan s = new TiepTan();
                try {
                    try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ThemTK.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=BenhVien;"
                            + "username=sa;password=123");
                    Statement ps = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                            ResultSet.CONCUR_READ_ONLY);
                    ResultSet rs = ps.executeQuery("select * from DanhSachNguoiPhatSo");
                    if (!rs.next()) {
                        s.setMSNV("300000");
                    } else {
                        rs.last();
                        String a = rs.getString("MSNV").trim();
                        //a = a.substring(2);
                        a = "" + (Integer.parseInt(a) + 1);
                        s.setMSNV(a);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ThemTK.class.getName()).log(Level.SEVERE, null, ex);
                }
                s.setName(txtName.getText());
                if (checkNam.isSelected()) {
                    s.setGioiTinh("Nam");
                } else if (checkNu.isSelected()) {
                    s.setGioiTinh("Nữ");
                }
                s.setNgaySinh(txtDate.getText());
                s.setSoDienThoai(txtSDT.getText());
                s.setDiaChi(txtAddress.getText());
                s.setMatKhau(txtNewPass.getText());
                s.setUserName(txtUser.getText());
                s.setEmail(txtEmail.getText());
                s.setCMND(txtID.getText());
                if (new DAO().addTKTiepTan(s) && (new DAO()).addTiepTan(s)) {
                    JOptionPane.showMessageDialog(txtDate, "thêm thành công");
                    list2.add(s);
                } else {
                    JOptionPane.showMessageDialog(txtDate, "tài khoản đã tồn tại");
                }
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNamActionPerformed
        if (checkNam.isSelected()) {
            checkNu.setSelected(false);
        } else {
            checkNu.setSelected(true);
        }
    }//GEN-LAST:event_checkNamActionPerformed

    private void checkNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNuActionPerformed
        if (checkNu.isSelected()) {
            checkNam.setSelected(false);
        } else {
            checkNam.setSelected(true);
        }
    }//GEN-LAST:event_checkNuActionPerformed

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        if (txtDate.isFocusable()) {
            warDate.setText("dd/mm/yyyy");
        } else {
            warDate.setText("");
        }
    }//GEN-LAST:event_txtDateFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtName.setText("");
        txtSDT.setText("");
        txtDate.setText("");
        txtID.setText("");
        txtEmail.setText("");
        txtAddress.setText("");
        txtUser.setText("");
        txtNewPass.setText("");
        txtConfirmPass.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtConfirmPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPassKeyPressed

    }//GEN-LAST:event_txtConfirmPassKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton checkNam;
    private javax.swing.JRadioButton checkNu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JComboBox<String> txtJob;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel warConfirmPass;
    private javax.swing.JLabel warDate;
    private javax.swing.JLabel warDiaChi;
    private javax.swing.JLabel warEmail;
    private javax.swing.JLabel warID;
    private javax.swing.JLabel warName;
    private javax.swing.JLabel warNewPass;
    private javax.swing.JLabel warSDT;
    private javax.swing.JLabel warUser;
    // End of variables declaration//GEN-END:variables
}
